"use client";
import Link from "next/link";
import {useState} from "react";

type Screen="home"|"news"|"article"|"jobs"|"education"|"results"|"tools"|"resume"|"account"|"search"|"notifications"|"follow";
const img=["/images/reference/hero-victoria.jpg","/images/reference/students.jpg","/images/reference/weather.jpg","/images/reference/sbi.svg"];
const stories=[
 ["West Bengal","WB Govt Recruitment 2025: রাজ্য সরকারি দপ্তরে 12,000+ শূন্যপদে নিয়োগ","2 ঘণ্টা আগে","12.5K"],
 ["পরীক্ষা","কলকাতায় আজ থেকে শুরু মাধ্যমিক পরীক্ষা 2025, জেনে নিন গুরুত্বপূর্ণ নির্দেশিকা","3 ঘণ্টা আগে","8.4K"],
 ["শিক্ষা","মাধ্যমিক 2025: পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ আপডেট","3 ঘণ্টা আগে","5.1K"],
 ["টেক","চাকরির বাজারে নতুন AI যুগ, কী কী সুযোগ আসছে","4 ঘণ্টা আগে","3.8K"],
 ["দেশ","ভারতে নতুন নিয়োগ: জানুন গুরুত্বপূর্ণ তথ্য","5 ঘণ্টা আগে","7.2K"]
];
const jobs=[["West Bengal Police Constable 2025","পশ্চিমবঙ্গ পুলিশ","কলকাতা, পশ্চিমবঙ্গ","₹21,700 - ₹69,100","16 May 2025"],["RBI Grade B Officer 2025","Reserve Bank of India","ভারত, যে কোনো স্থান","₹55,000 - ₹1,05,000","30 Apr 2025"],["TCS Digital Hiring 2025","Tata Consultancy Services","ভারত, বিভিন্ন শহর","₹3.5 - 5 LPA","30 Apr 2025"]];
function Logo(){return <Link href="/bn" className="mr-logo"><span>কি</span><b>চলছে</b><small>Kicholche</small></Link>}
function Header({title,back=true}:{title?:string;back?:boolean}){return <header className="mr-head"><div className="mr-top">{back?<Link href="/bn" className="mr-back">‹</Link>:<span className="mr-menu">☰</span>}{title?<strong>{title}</strong>:<Logo/>}<div className="mr-head-icons"><span>⌕</span><span>♧</span><span>⋮</span></div></div>{!title&&<div className="mr-home-actions"><button>🌐 বাংলা⌄</button><button>♢</button><button>☰</button></div>}{!title&&<div className="mr-search">⌕ <span>খবর, চাকরি, শিক্ষা, ফলাফল, ট্রেন্ড খুঁজুন...</span><b>×</b></div>}</header>}
function Bottom({active="home"}:{active?:string}){return <nav className="mr-bottom">{[["⌂","হোম","home","/bn"],["⌕","খবর","news","/bn/news"],["♡","অনুসন্ধান","search","/search"],["⁙","টুলস","tools","/ai-tools"],["♙","প্রোফাইল","account","/account"]].map(([i,t,k,h])=><Link className={active===k?"on":""} key={k} href={h}><b>{i}</b><span>{t}</span></Link>)}</nav>}
function Tabs({items=["সকল","ব্রেকিং","ট্রেন্ডিং","পরিষ্কার","ফল"]}:{items?:string[]}){return <div className="mr-tabs">{items.map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div>}
function StoryCard({i=0,compact=false}:{i?:number;compact?:boolean}){const s=stories[i%stories.length];return <Link href="/article?locale=bn" className={compact?"mr-story compact":"mr-story"}><img src={img[(i+1)%3]} /><div><em>{s[0]}</em><b>{s[1]}</b><small>◷ {s[2]}　•　◉ {s[3]} views</small></div></Link>}
function Home(){return <div className="mr-screen"><Header back={false}/><div className="mr-breaking"><b>⚡ Breaking News</b><span>{stories[0][1]}</span><a>See All ›</a></div><section className="mr-hero"><img src={img[0]}/><div><em>West Bengal</em><h1>{stories[1][1]}</h1><small>◷ 2 ঘণ্টা আগে　•　◉ 12.5K views</small></div></section><div className="mr-quick">{["💼 চাকরি","🎓 শিক্ষা","▣ পরীক্ষা","♧ ফলাফল","🏛 সরকারী","☁ আবহাওয়া","⚽ খেলা","••• আরও"].map(x=><Link href="/bn/news" key={x}>{x}</Link>)}</div><div className="mr-section-head"><b>আজকের ব্রিফিং</b><Link href="/bn/news">আরও দেখুন →</Link></div><section className="mr-list">{[0,1,2,3].map(i=><StoryCard i={i} key={i}/>)}</section><section className="mr-bluebox"><b>সরকারি ফলাফল ও জরুরি আপডেট</b><span>এক জায়গায় সব গুরুত্বপূর্ণ তথ্য</span></section><Bottom/></div>}
function News(){return <div className="mr-screen"><Header title="সর্বশেষ খবর"/><Tabs/><main className="mr-list page-list">{[0,1,2,3,4].map(i=><StoryCard i={i} key={i}/>)}</main><Bottom active="news"/></div>}
function Article(){return <div className="mr-screen"><Header title=""/><article className="mr-article"><img className="article-cover" src={img[0]}/><em>West Bengal</em><h1>কলকাতায় আজ থেকে শুরু মাধ্যমিক পরীক্ষা 2025, জেনে নিন গুরুত্বপূর্ণ নির্দেশিকা</h1><div className="mr-author"><span>কি</span><div><b>Kicholche Desk</b><small>২ ঘণ্টা আগে　•　12.5K views</small></div><button>♧</button></div><div className="share-row"><button>f</button><button>◉</button><button>𝕏</button><button>↗</button><button>♧</button></div><p>আজ, ১০ সেপ্টেম্বর ২০২৫ থেকে শুরু হচ্ছে মাধ্যমিক পরীক্ষা। পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ নির্দেশিকা, সময়সূচি এবং পরীক্ষাকেন্দ্র সম্পর্কিত তথ্য এখানে একসঙ্গে দেওয়া হলো।</p><div className="info blue"><b>🔵 গুরুত্বপূর্ণ নির্দেশিকা:</b><span>• পরীক্ষা শুরু: সকাল ১০:০০ টায়</span><span>• পরীক্ষার আগে কেন্দ্র ও আসন যাচাই করুন</span><span>• নির্দিষ্ট সময়ের আগে পৌঁছাতে হবে</span></div><div className="info red"><b>🔴 বিশেষ সতর্কতা:</b><span>পরীক্ষার্থীদের প্রয়োজনীয় পরিচয়পত্র সঙ্গে রাখতে হবে।</span></div><StoryCard i={2}/></article><Bottom active="news"/></div>}
function Jobs(){return <div className="mr-screen"><Header title="চাকরি"/><Tabs items={["সকল","সরকারি","বেসরকারি","স্থানীয়","ইন্টার্নশিপ"]}/><div className="mr-filters"><button>অনুসন্ধান⌄</button><button>যোগ্যতা⌄</button><button>চাকরির ধরন⌄</button><button>⚙</button></div><main className="job-list">{jobs.map((j,i)=><Link className="job-card" href="/job" key={j[0]}><div className="job-icon">{i===0?"🛡":i===1?"🏛":"TCS"}</div><div><em>{i===0?"সরকারি":i===1?"কেন্দ্রীয়":"বেসরকারি"}</em><b>{j[0]}</b><small>◉ {j[1]}</small><small>📍 {j[2]}</small><strong>◉ {j[3]}</strong><small>⏱ Last Date: {j[4]}</small><button>বিস্তারিত দেখুন →</button></div></Link>)}</main><Bottom active="news"/></div>}
function Education(){return <div className="mr-screen"><Header title="শিক্ষা"/><Tabs items={["স্কুল","কলেজ","বিশ্ববিদ্যালয়","ভর্তি"]}/><div className="mr-filters"><button>সকল নোটিশ⌄</button><button>সকল জেলা⌄</button></div><main className="mr-list page-list">{[2,1,0,3].map(i=><StoryCard i={i} key={i}/>)}</main><Bottom active="news"/></div>}
function Results(){return <div className="mr-screen"><Header title="ফলাফল"/><Tabs items={["মাধ্যমিক","উচ্চমাধ্যমিক","বিশ্ববিদ্যালয়","অন্যান্য"]}/><main className="result-list">{["মাধ্যমিক ২০২৫ ফলাফল","উচ্চমাধ্যমিক ২০২৫ ফলাফল","WBJEE ২০২৫ রেজাল্ট","বনরক্ষী রিক্রুটমেন্ট ২০২৫"].map((x,i)=><div className="result-card" key={x}><span>{i<2?"◉":"◌"}</span><div><b>{x}</b><small>পশ্চিমবঙ্গ শিক্ষা পর্ষদ</small><em>ফলাফল প্রকাশিত: 08 May 2025</em><button>রেজাল্ট দেখুন →</button></div></div>)}<div className="mr-purple">📣 মাধ্যমিকের পরবর্তী গুরুত্বপূর্ণ আপডেট এখানে পাবেন</div></main><Bottom active="news"/></div>}
function Tools(){return <div className="mr-screen"><Header title="AI & টুলস"/><section className="tools-hero"><div><b>স্মার্ট টুলস, সহজ জীবন</b><small>দ্রুত ও সহজে কাজ করুন</small></div><span>🤖</span></section><Tabs items={["সব","PDF","ছবি","টেক্সট","ভাষা"]}/><div className="tool-grid">{[["📄","PDF to Text","ছবি থেকে টেক্সট"],["🖼","Image to Text","ছবি থেকে টেক্সট"],["🗣","Translator","ভাষা অনুবাদ"],["📋","Resume Maker","সিভি তৈরি করুন"],["🧮","EMI Calculator","EMI হিসাব করুন"],["🎓","GPA Calculator","GPA হিসাব করুন"]].map(([a,b,c])=><Link href={b==="Resume Maker"?"/ai-tools/resume-maker":"/ai-tools"} className="tool-card" key={b}><b>{a}</b><strong>{b}</strong><small>{c}</small></Link>)}</div><Link className="mr-primary" href="/ai-tools">সব টুলস দেখুন →</Link><Bottom active="tools"/></div>}
function Resume(){return <div className="mr-screen"><Header title="Resume Maker"/><section className="resume-hero"><div><b>আপনার প্রফেশনাল রিজিউমে তৈরি করুন</b><small>সহজ, দ্রুত এবং সম্পূর্ণ ফ্রি</small><button>নতুন রিজিউমে তৈরি করুন →</button></div><span>📄</span></section><div className="resume-features"><span>▣<b>Multiple Templates</b></span><span>◉<b>Live Preview</b></span><span>▣<b>PDF Download</b></span></div><h3>জনপ্রিয় টেমপ্লেট</h3><div className="template-row">{["Modern","Classic","Creative"].map((x,i)=><div key={x}><img src={img[(i+1)%3]}/><b>{x}</b></div>)}</div><h3>ব্যক্তিগত বিবরণ</h3><ul className="resume-points"><li>নাম ও যোগাযোগ</li><li>শিক্ষা</li><li>কাজের অভিজ্ঞতা</li><li>দক্ষতা</li><li>প্রজেক্ট</li><li>DOCX (শীঘ্রই)</li></ul><Bottom active="tools"/></div>}
function Account(){return <div className="mr-screen"><Header title="অ্যাকাউন্ট"/><main className="account-page"><div className="guest"><span>👤</span><b>Guest User</b><small>লগইন করে আরও সুবিধা নিন</small></div>{["সেভ করা খবর","সেভ করা চাকরি","সাম্প্রতিক ব্যবহার","পছন্দের ক্যাটাগরি","নোটিফিকেশন সেটিংস","ভাষা পরিবর্তন","থিম/লাইট মোড"].map((x,i)=><Link href="/account" key={x}><b>{["♡","▣","◷","⚙","🔔","◎","☀"][i]}</b>{x}<span>›</span></Link>)}<div className="account-social"><b>কিচলচে</b><small>আমাদের সাথে যুক্ত থাকুন</small><div><button>YouTube</button><button>Facebook</button></div></div></main><Bottom active="account"/></div>}
function Search(){return <div className="mr-screen"><Header title="অনুসন্ধান"/><div className="search-big">⌕ <span>কি খুঁজছেন?</span><button>⌕</button></div><Tabs items={["সব","খবর","চাকরি","ফলাফল","শিক্ষা","টুলস"]}/><div className="recent-search">{["WB Police recruitment","Madhyamik result 2025","TCS hiring 2025","Resume maker","Weather Kolkata","SBI Clerk 2025"].map(x=><Link href="/search" key={x}>⌕ {x}<span>›</span></Link>)}</div><button className="mr-primary">সকল ফলাফল দেখুন →</button><Bottom active="search"/></div>}
function Notifications(){return <div className="mr-screen"><Header title="নোটিফিকেশন"/><Tabs items={["সব","খবর","চাকরি","ফলাফল","সাবস্ক্রাইব"]}/><div className="notify-list">{stories.slice(0,5).map((s,i)=><Link href="/article" key={i}><b>{["🔴","🟢","🟣","🔵","🟠"][i]}</b><div><strong>{s[0]}</strong><span>{s[1]}</span><small>{i+2} ঘণ্টা আগে</small></div></Link>)}</div><div className="notify-settings">⚙ নোটিফিকেশন সেটিংস</div><Bottom active="search"/></div>}
function Follow(){return <div className="mr-screen"><Home/><div className="follow-scrim"><div className="follow-modal"><button className="close">×</button><Logo/><h2>আপ খবর, সব সময়</h2><p>নতুন আপডেট পেতে আমাদের সাথে যুক্ত থাকুন!</p><div><a>YouTube</a><a>Facebook</a></div><b>আমাদের বিশেষ</b><Tabs items={["সকল","চাকরি","শিক্ষা","ফলাফল"]}/></div></div></div>}
export default function MobileReference({screen}:{screen:Screen}){if(screen==="home")return <Home/>;if(screen==="news")return <News/>;if(screen==="article")return <Article/>;if(screen==="jobs")return <Jobs/>;if(screen==="education")return <Education/>;if(screen==="results")return <Results/>;if(screen==="tools")return <Tools/>;if(screen==="resume")return <Resume/>;if(screen==="account")return <Account/>;if(screen==="search")return <Search/>;if(screen==="notifications")return <Notifications/>;return <Follow/>}
