import Link from "next/link";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import ThemeToggle from "@/components/ThemeToggle";
import MobileMenu from "@/components/MobileMenu";

const copy={
bn:{location:"শিলিগুড়ি, পশ্চিমবঙ্গ",date:"২৫ সেপ্টেম্বর ২০২৬",today:"আজকের আপডেট",search:"খবর, চাকরি, রেজাল্ট বা যেকোনো কিছু খুঁজুন...",searchBtn:"খুঁজুন",nav:["খবর","চাকরি","শিক্ষা","রেজাল্ট","সরকারি আপডেট","সিলিগুড়ি","উত্তরবঙ্গ","দেশ","ভারত","বিশ্ব","AI Tools"],ticker:"চাকরি আপডেট",tickerText:"পশ্চিমবঙ্গে আগামী ৪৮ ঘণ্টায় ভারী বৃষ্টির সম্ভাবনা — সতর্ক থাকুন",latest:"সর্বশেষ খবর",all:"সব দেখুন →",heroTag:"রাজ্য · ২ ঘণ্টা আগে",heroTitle:"পশ্চিমবঙ্গে আগামী ৪৮ ঘণ্টায় ভারী বৃষ্টির সম্ভাবনা, সতর্কতা জারি",heroText:"আবহাওয়া দপ্তরের নতুন আপডেট ও জেলার ভিত্তিতে সতর্কতার বিস্তারিত তথ্য এক জায়গায়।",read:"বিস্তারিত পড়ুন →",trending:"আজকের ট্রেন্ডিং",latestNews:"সর্বশেষ খবর",weather:"আজকের আবহাওয়া",weatherText:"শিলিগুড়ি · হালকা মেঘলা",jobsTitle:"চাকরির আপডেট",stay:"কি চলে-এ থাকুন",stayText:"প্রতিদিনের গুরুত্বপূর্ণ আপডেট মিস করবেন না।",lowerTitle:"শিক্ষা · রেজাল্ট · সরকারি আপডেট",footer:"প্রতিদিনের দরকারি খবর ও আপডেট।",quick:"দ্রুত লিংক",info:"তথ্য",follow:"আমাদের অনুসরণ করুন",home:"হোম",jobs:"চাকরি",news:"খবর",categories:"বিভাগ",account:"অ্যাকাউন্ট",desc:"গুরুত্বপূর্ণ তথ্য, বিস্তারিত আপডেট এবং প্রয়োজনীয় লিংক এক জায়গায় পাবেন।",more:"সব খবর →"},
hi:{location:"सिलीगुड़ी, पश्चिम बंगाल",date:"25 सितंबर 2026",today:"आज के अपडेट",search:"समाचार, नौकरी, परिणाम या कुछ भी खोजें...",searchBtn:"खोजें",nav:["समाचार","नौकरियाँ","शिक्षा","परिणाम","सरकारी अपडेट","सिलीगुड़ी","उत्तर बंगाल","देश","भारत","विश्व","AI टूल्स"],ticker:"नौकरी अपडेट",tickerText:"पश्चिम बंगाल में अगले 48 घंटों में भारी बारिश की संभावना — सतर्क रहें",latest:"ताज़ा समाचार",all:"सभी देखें →",heroTag:"राज्य · 2 घंटे पहले",heroTitle:"पश्चिम बंगाल में अगले 48 घंटों में भारी बारिश की संभावना, चेतावनी जारी",heroText:"मौसम विभाग के नए अपडेट और जिलेवार चेतावनी की पूरी जानकारी एक जगह।",read:"विस्तार से पढ़ें →",trending:"आज ट्रेंडिंग",latestNews:"ताज़ा खबरें",weather:"आज का मौसम",weatherText:"सिलीगुड़ी · हल्के बादल",jobsTitle:"नौकरी अपडेट",stay:"Kicholche से जुड़े रहें",stayText:"हर दिन के महत्वपूर्ण अपडेट न चूकें।",lowerTitle:"शिक्षा · परिणाम · सरकारी अपडेट",footer:"हर दिन की ज़रूरी खबरें और अपडेट।",quick:"त्वरित लिंक",info:"जानकारी",follow:"हमें फॉलो करें",home:"होम",jobs:"नौकरियाँ",news:"समाचार",categories:"श्रेणियाँ",account:"खाता",desc:"महत्वपूर्ण जानकारी, विस्तृत अपडेट और उपयोगी लिंक एक जगह।",more:"सभी खबरें →"},
en:{location:"Siliguri, West Bengal",date:"25 September 2026",today:"Today's updates",search:"Search news, jobs, results or anything...",searchBtn:"Search",nav:["News","Jobs","Education","Results","Government Updates","Siliguri","North Bengal","India","National","World","AI Tools"],ticker:"JOB UPDATES",tickerText:"Heavy rain likely in West Bengal over the next 48 hours — stay alert",latest:"Latest News",all:"View all →",heroTag:"State · 2 hours ago",heroTitle:"Heavy rain likely in West Bengal over the next 48 hours; alert issued",heroText:"Weather department updates and district-wise alerts, all in one place.",read:"Read full story →",trending:"Trending Today",latestNews:"Latest Stories",weather:"Today's Weather",weatherText:"Siliguri · Partly cloudy",jobsTitle:"Job Updates",stay:"Stay connected with Kicholche",stayText:"Don't miss important daily updates.",lowerTitle:"Education · Results · Government Updates",footer:"Useful daily news and updates.",quick:"Quick Links",info:"Information",follow:"Follow Us",home:"Home",jobs:"Jobs",news:"News",categories:"Categories",account:"Account",desc:"Important information, detailed updates and useful links in one place.",more:"All news →"}
} as const;
const stories={
bn:[["রাজ্য","পশ্চিমবঙ্গে আগামী ৪৮ ঘণ্টায় ভারী বৃষ্টির সম্ভাবনা, সতর্কতা জারি"],["চাকরি","নতুন সরকারি নিয়োগে আবেদন শুরু, জেনে নিন যোগ্যতা ও শেষ তারিখ"],["শিক্ষা","মাধ্যমিক পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ নতুন নির্দেশিকা"],["দেশ","নতুন শিক্ষানীতি নিয়ে একাধিক গুরুত্বপূর্ণ আপডেট"]],
hi:[["राज्य","पश्चिम बंगाल में अगले 48 घंटों में भारी बारिश की संभावना"],["नौकरी","नई सरकारी भर्ती के आवेदन शुरू, योग्यता और अंतिम तारीख जानें"],["शिक्षा","माध्यमिक परीक्षार्थियों के लिए महत्वपूर्ण नई सूचना"],["देश","नई शिक्षा नीति से जुड़े महत्वपूर्ण अपडेट"]],
en:[["State","Heavy rain likely in West Bengal over the next 48 hours"],["Jobs","Applications open for a new government recruitment"],["Education","Important new notice for secondary exam candidates"],["India","Key updates related to the new education policy"]]
};
const jobTitles={bn:["SSC নিয়োগ ২০২৫","মাধ্যমিক ২০২৫ ফলাফল","ভারত-পাকিস্তান ম্যাচ","আবহাওয়া আপডেট","চাকরির আবেদনের শেষ তারিখ"],hi:["SSC भर्ती 2025","माध्यमिक 2025 परिणाम","भारत-पाकिस्तान मैच","मौसम अपडेट","नौकरी आवेदन की अंतिम तारीख"],en:["SSC Recruitment 2025","Madhyamik Results 2025","India–Pakistan Match","Weather Update","Job Application Deadline"]};
const categoryLabels={bn:["খবর","চাকরি","শিক্ষা","রেজাল্ট","সরকারি"],hi:["समाचार","नौकरियाँ","शिक्षा","परिणाम","सरकारी"],en:["News","Jobs","Education","Results","Government"]};
const lowerTitles={bn:["মাধ্যমিক ২০২৫: পরীক্ষার গুরুত্বপূর্ণ তথ্য","আজ প্রকাশিত নতুন সরকারি বিজ্ঞপ্তি","রেজাল্ট দেখার পদ্ধতি ও অফিসিয়াল লিংক"],hi:["माध्यमिक 2025: परीक्षा की महत्वपूर्ण जानकारी","आज जारी नई सरकारी अधिसूचना","परिणाम देखने का तरीका और आधिकारिक लिंक"],en:["Madhyamik 2025: Important exam information","New government notice released today","How to check results and official links"]};
function Logo({locale}:{locale:string}){return <Link href={"/"+locale} className="brand"><span className="brand-mark">কি</span><b>চলে</b></Link>}
function Placeholder(){return <div className="photo-placeholder"/>}
export default async function LocaleHomePage({params}:{params:Promise<{locale:string}>}) {
 const {locale:raw}=await params;const locale=(["bn","hi","en"].includes(raw)?raw:"bn") as "bn"|"hi"|"en";const t=copy[locale];const latest=stories[locale];const jobs=jobTitles[locale];const categories=categoryLabels[locale];const lower=lowerTitles[locale];const prefix="/"+locale;
 return <main className="kc">
 <div className="topbar"><div className="topbar-inner"><span>● {t.location}</span><span>{t.date}</span><span>{t.today}</span><i/><LanguageSwitcher/></div></div>
 <header className="head"><div className="head-main"><Logo locale={locale}/><form className="search" action="/search"><input type="hidden" name="locale" value={locale}/><input name="q" placeholder={t.search}/><button>{t.searchBtn}</button></form><div className="head-icons"><Link href={prefix+"/news"} aria-label={t.latest}>♢</Link><ThemeToggle/></div></div><nav>{t.nav.map((x,i)=><Link key={x} href={i===1?prefix+"/jobs":prefix+"/news"}>{x}</Link>)}</nav></header>
 <div className="mobile-head"><MobileMenu locale={locale}/><Logo locale={locale}/><div className="mobile-actions"><ThemeToggle/><Link href={"/account?locale="+locale} aria-label={t.account}>●</Link></div><LanguageSwitcher/></div>
 <div className="mobile-search"><form action="/search"><input type="hidden" name="locale" value={locale}/><input name="q" placeholder={t.search}/><button>{t.searchBtn}</button></form></div>
 <div className="ticker"><b>⚡ {t.ticker}</b><span>{t.tickerText}</span><strong>›</strong></div>
 <div className="wrap"><section className="hero"><article className="hero-main"><Placeholder/><div className="hero-copy"><small>{t.heroTag}</small><h1>{latest[0][1]}</h1><p>{t.heroText}</p><Link href={prefix+"/news"}>{t.read}</Link></div></article><aside><div className="aside-title"><h2>{t.latest}</h2><Link href={prefix+"/news"}>{t.all}</Link></div>{latest.map(([tag,title])=><Link className="aside-item" href={prefix+"/news"} key={title}><small>{tag}</small><h3>{title}</h3><span>{locale==="en"?"20 minutes ago":locale==="hi"?"20 मिनट पहले":"২০ মিনিট আগে"}</span></Link>)}</aside></section>
 <section className="chips">{categories.map((x,i)=><Link href={prefix+"/news?category="+i} key={x}><span>{["▣","▰","🎓","▤","♜"][i]}</span>{x}</Link>)}</section>
 <section className="content-grid"><div className="main-col"><div className="section-head"><h2>{t.trending}</h2><Link href={prefix+"/trending"}>{t.all}</Link></div><div className="trending">{jobs.map((x,i)=><Link href={prefix+"/jobs"} key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><em>↑ Trending</em></Link>)}</div><div className="section-head latest-head"><h2>{t.latestNews}</h2><Link href={prefix+"/news"}>{t.more}</Link></div><div className="latest-list">{[...latest,...latest].map(([tag,title],i)=><Link className="news-row" href={prefix+"/news"} key={i}><Placeholder/><div><small>{tag} · {i+2} {locale==="en"?"hours ago":locale==="hi"?"घंटे पहले":"ঘণ্টা আগে"}</small><h3>{title}</h3><p>{t.desc}</p></div></Link>)}</div></div>
 <aside className="right-col"><div className="weather"><small>{t.weather}</small><b>☀️ 28°</b><span>{t.weatherText}</span><em>{locale==="en"?"Humidity 72%":locale==="hi"?"नमी 72%":"আর্দ্রতা 72%"}</em></div><div className="side-box"><div className="side-title"><h2>{t.jobsTitle}</h2><Link href={prefix+"/jobs"}>{t.all}</Link></div>{jobs.slice(0,3).map(x=><Link href={prefix+"/jobs"} key={x}><b>{x}</b><small>📍 {t.location}</small></Link>)}</div><div className="side-box follow"><h2>{t.stay}</h2><p>{t.stayText}</p><div><a href="https://www.youtube.com/" target="_blank" rel="noreferrer">▶ YouTube</a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer">f Facebook</a></div></div></aside></section>
 <section className="lower"><div className="section-head"><h2>{t.lowerTitle}</h2><Link href={prefix+"/news"}>{t.all}</Link></div><div className="lower-grid">{lower.map((x,i)=><Link href={prefix+"/news"} key={x}><div><b>0{i+1}</b></div><h3>{x}</h3><p>{t.desc}</p></Link>)}</div></section></div>
 <footer><div><Logo locale={locale}/><p>{t.footer}</p></div><div><b>{t.quick}</b><p>{t.nav.slice(0,5).join(" · ")}</p></div><div><b>{t.info}</b><p>{locale==="en"?"Contact · Privacy · Terms":locale==="hi"?"संपर्क · गोपनीयता · शर्तें":"যোগাযোগ · গোপনীয়তা · শর্তাবলি"}</p></div><div><b>{t.follow}</b><p>YouTube · Facebook<br/>Instagram · X</p></div><small>© 2026 Kicholche. All Rights Reserved.</small></footer>
 <nav className="bottom-nav"><Link className="active" href={prefix}>⌂<span>{t.home}</span></Link><Link href={prefix+"/jobs"}>▣<span>{t.jobs}</span></Link><Link href={prefix+"/news"}>▤<span>{t.news}</span></Link><Link href={prefix+"/news?category=all"}>▦<span>{t.categories}</span></Link><Link href={"/account?locale="+locale}>●<span>{t.account}</span></Link></nav>
 </main>;
}