import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import ThemeToggle from "@/components/ThemeToggle";
import MobileMenu from "@/components/MobileMenu";
import NotificationBell from "@/components/NotificationBell";
import HomeHeroCarousel from "@/components/HomeHeroCarousel";
import MobileReference from "@/components/MobileReference";

type Locale = "bn"|"hi"|"en";
const locales:Locale[]=["bn","hi","en"];
const T:any={
 bn:{loc:"শিলিগুড়ি, পশ্চিমবঙ্গ",date:"২৫ সেপ্টেম্বর ২০২৬",search:"খবর, চাকরি, শিক্ষা, ফলাফল, ট্রেন্ড খুঁজুন...",home:"Home",latest:"Latest",breaking:"Breaking",trending:"Trending",jobs:"Jobs",education:"Education",exams:"Exams",results:"Results",government:"Government",weather:"Weather",lottery:"Lottery Result",sports:"Sports",business:"Business",technology:"Technology",ent:"Entertainment",tools:"AI Tools",more:"আরও দেখুন →",read:"বিস্তারিত পড়ুন →",allJobs:"চাকরি",quick:"গুরুত্বপূর্ণ লিংক",categories:"জনপ্রিয় ক্যাটাগরি",follow:"আমাদের অনুসরণ করুন",account:"প্রোফাইল",recent:"সাম্প্রতিক খবর",popular:"জনপ্রিয়",trend:"ট্রেন্ডিং",all:"সব দেখুন →",ai:"AI টুলস",news:"খবর",resultsTitle:"ফলাফল",governmentUpdate:"সরকারি আপডেট",importantLinks:"গুরুত্বপূর্ণ লিংক",copyright:"© 2026 Kicholche. All Rights Reserved.",update:"আপডেট",today:"আজকের আপডেট",view:"দেখুন",lastDate:"শেষ তারিখ",board:"মাধ্যমিক শিক্ষা পর্ষদ",toolsPdf:"PDF টুলস",toolsImage:"ইমেজ টুলস",toolsText:"টেক্সট টুলস",toolsLanguage:"ভাষা টুলস",toolsCareer:"ক্যারিয়ার টুলস",toolsStudent:"স্টুডেন্ট টুলস",toolsFinance:"ফাইন্যান্স টুলস",toolsDeveloper:"ডেভেলপার টুলস",easyTool:"দ্রুত ও সহজ টুল"},
 hi:{loc:"सिलीगुड़ी, पश्चिम बंगाल",date:"25 सितंबर 2026",search:"समाचार, नौकरी, शिक्षा, परिणाम खोजें...",home:"Home",latest:"Latest",breaking:"Breaking",trending:"Trending",jobs:"Jobs",education:"Education",exams:"Exams",results:"Results",government:"Government",weather:"Weather",lottery:"Lottery Result",sports:"Sports",business:"Business",technology:"Technology",ent:"Entertainment",tools:"AI Tools",more:"और देखें →",read:"विस्तार से पढ़ें →",allJobs:"नौकरी",quick:"महत्वपूर्ण लिंक",categories:"लोकप्रिय श्रेणियाँ",follow:"हमसे जुड़ें",account:"प्रोफ़ाइल",recent:"हाल की खबरें",popular:"लोकप्रिय",trend:"ट्रेंडिंग",all:"सभी देखें →",ai:"AI टूल्स",news:"समाचार",resultsTitle:"परिणाम",governmentUpdate:"सरकारी अपडेट",importantLinks:"महत्वपूर्ण लिंक",copyright:"© 2026 Kicholche. All Rights Reserved.",update:"अपडेट",today:"आज का अपडेट",view:"देखें",lastDate:"अंतिम तिथि",board:"माध्यमिक शिक्षा बोर्ड",toolsPdf:"PDF टूल्स",toolsImage:"इमेज टूल्स",toolsText:"टेक्स्ट टूल्स",toolsLanguage:"भाषा टूल्स",toolsCareer:"करियर टूल्स",toolsStudent:"स्टूडेंट टूल्स",toolsFinance:"फाइनेंस टूल्स",toolsDeveloper:"डेवलपर टूल्स",easyTool:"तेज़ और आसान टूल"},
 en:{loc:"Siliguri, West Bengal",date:"25 September 2026",search:"Search news, jobs, education, results...",home:"Home",latest:"Latest",breaking:"Breaking",trending:"Trending",jobs:"Jobs",education:"Education",exams:"Exams",results:"Results",government:"Government",weather:"Weather",lottery:"Lottery Result",sports:"Sports",business:"Business",technology:"Technology",ent:"Entertainment",tools:"AI Tools",more:"View more →",read:"Read full story →",allJobs:"Jobs",quick:"Important Links",categories:"Popular Categories",follow:"Follow Us",account:"Profile",recent:"Latest News",popular:"Popular",trend:"Trending",all:"View all →",ai:"AI Tools",news:"News",resultsTitle:"Results",governmentUpdate:"Government Updates",importantLinks:"Important Links",copyright:"© 2026 Kicholche. All Rights Reserved.",update:"Updates",today:"Today’s Updates",view:"View",lastDate:"Last Date",board:"Education Board",toolsPdf:"PDF Tools",toolsImage:"Image Tools",toolsText:"Text Tools",toolsLanguage:"Language Tools",toolsCareer:"Career Tools",toolsStudent:"Student Tools",toolsFinance:"Finance Tools",toolsDeveloper:"Developer Tools",easyTool:"Quick & Easy Tool"}
};function titleOf(r:any,l:Locale){const a=r?.article_translations||r?.job_translations||[];return a.find((x:any)=>x.locale===l)?.title||a.find((x:any)=>x.locale==="bn")?.title||a[0]?.title||r?.slug||""}
function excerptOf(r:any,l:Locale){const a=r?.article_translations||[];return a.find((x:any)=>x.locale===l)?.excerpt||a.find((x:any)=>x.locale==="bn")?.excerpt||""}
function catOf(r:any,l:Locale,f:string){const c=Array.isArray(r?.categories)?r.categories[0]:r?.categories;return c?.["name_"+l]||c?.name_bn||f}
const FALLBACK_IMAGES=["/images/reference/hero-victoria.jpg","/images/reference/sbi.svg","/images/reference/students.jpg","/images/reference/weather.jpg"];
function mediaUrl(s:any,rows:any,purpose:string){const m=rows.find((x:any)=>x.purpose===purpose);return m?s.storage.from("media").getPublicUrl(m.storage_path).data.publicUrl:""}
function Logo({locale}:{locale:Locale}){return <Link className="kc-logo" href={"/"+locale}><span className="kc-logo-icon">ক</span><span><b>কিচলচে</b><small>Kicholche</small></span></Link>}
function Img({src,kind="news",alt=""}:{src?:string,kind?:string,alt?:string}){const fallback=kind==="job"?FALLBACK_IMAGES[1]:kind==="news"?FALLBACK_IMAGES[2]:FALLBACK_IMAGES[0];return <img className="kc-img" src={src||fallback} alt={alt}/> }
function Card({r,l,src}:{r:any,l:Locale,src?:string}){return <Link className="news-card" href={r?.slug?"/article?slug="+encodeURIComponent(r.slug)+"&locale="+l:"/"+l+"/news"}><Img src={src} alt={titleOf(r,l)}/><div><small>{catOf(r,l,"News")}</small><h3>{titleOf(r,l)}</h3><p>{excerptOf(r,l)}</p></div></Link>}export default async function LocaleHomePage({params}:{params:Promise<{locale:string}>}){
 const raw=(await params).locale;const l=(locales.includes(raw as Locale)?raw:"bn") as Locale;const t=T[l];const pre="/"+l;const s=await createClient(); const {data:{user}}=await s.auth.getUser();
 const [{data:articles},{data:jobs},{data:media}]=await Promise.all([
  s.from("articles").select("id,slug,publish_at,featured,breaking,trending,featured_media_id,article_translations(title,excerpt,locale),categories(slug,name_bn,name_hi,name_en)").eq("status","published").order("publish_at",{ascending:false,nullsFirst:false}).limit(12),
  s.from("jobs").select("id,slug,job_type,location,job_translations(title,locale)").eq("status","published").order("created_at",{ascending:false}).limit(6),
  s.from("media").select("id,storage_path,purpose,alt_text,created_at").in("purpose",["homepage","news_feature","news_thumb","trending","job"]).order("created_at",{ascending:false})
 ]);
 const A=articles||[],J=jobs||[],M=media||[]; const notifications=user ? [...A.slice(0,5).map((r:any)=>({id:"article-"+r.id,title:titleOf(r,l),href:"/article?slug="+encodeURIComponent(r.slug)+"&locale="+l,type:"News"})),...J.slice(0,3).map((r:any)=>({id:"job-"+r.id,title:titleOf(r,l),href:"/"+l+"/jobs",type:"Jobs"}))] : [];const hero=A.find((x:any)=>x.featured)||A[0];const latest=A.slice(0,5);const trend=A.filter((x:any)=>x.trending).slice(0,5).length?A.filter((x:any)=>x.trending).slice(0,5):A.slice(0,5);
 const hmedia=hero?.featured_media_id?M.find((x:any)=>x.id===hero.featured_media_id):null;const hurl=hmedia?s.storage.from("media").getPublicUrl(hmedia.storage_path).data.publicUrl:mediaUrl(s,M,"homepage")||FALLBACK_IMAGES[0];
 const slidesIndex=(rows:any,r:any)=>Math.max(0,rows.findIndex((x:any)=>x.id===r.id))%FALLBACK_IMAGES.length;
 const slides=A.slice(0,6).map((r:any)=>{const m=r.featured_media_id?M.find((x:any)=>x.id===r.featured_media_id):null;return{id:r.id,title:titleOf(r,l),excerpt:excerptOf(r,l),tag:"Top News",href:r.slug?"/article?slug="+encodeURIComponent(r.slug)+"&locale="+l:pre+"/news",image:m?s.storage.from("media").getPublicUrl(m.storage_path).data.publicUrl:FALLBACK_IMAGES[slidesIndex(A,r)],alt:titleOf(r,l)}}); return <><div className="reference-mobile-home"><MobileReference screen="home"/></div><main className="kicholche">
 <div className="topline"><span>📍 {t.loc}</span><span>{t.date}</span><span>{t.today}</span><span className="top-spacer"/></div>
 <header className="head"><div className="head-row"><Logo locale={l}/><form className="main-search" action="/search"><input type="hidden" name="locale" value={l}/><input name="q" placeholder={t.search}/><button>⌕</button></form><div className="head-tools"><LanguageSwitcher/><ThemeToggle/>{user&&<NotificationBell locale={l} items={notifications}/>}<MobileMenu locale={l}/></div></div>
 <nav className="nav">{[["",t.home],["/news",t.latest],["/news?breaking=1",t.breaking],["/trending",t.trending],["/news?category=education",t.education],["/news?category=exams",t.exams],["/news?category=results",t.results],["/jobs",t.jobs],["/news?category=government",t.government],["/results?type=lottery",t.lottery],["/news?category=sports",t.sports],["/news?category=business",t.business],["/news?category=entertainment",t.ent],["/news?category=technology",t.technology],["/ai-tools",t.tools]].map(([h,x])=><Link key={x} href={pre+h}>{x}</Link>)}</nav></header>
 <div className="mobile-head"><MobileMenu locale={l}/><Link className="mobile-brand" href={pre}><span>কি</span><b>চলছে</b><small>Kicholche</small></Link><div className="mobile-actions"><LanguageSwitcher/><NotificationBell locale={l} items={notifications}/><ThemeToggle/></div></div>
 <div className="mobile-search"><form action="/search"><input type="hidden" name="locale" value={l}/><input name="q" placeholder={t.search}/><button>⌕</button></form></div>
 <div className="breaking"><b>⚡ {t.breaking}</b><div className="breaking-track"><span>{hero?titleOf(hero,l):t.today}</span></div><i>‹　›</i></div>
 <div className="page-wrap">  <section className="hero-grid"><HomeHeroCarousel slides={slides}/><aside className="latest-panel"><div className="panel-title"><b className="latest-tab">{t.recent}</b><span className="popular-tab">{t.popular}</span><span className="trending-tab">{t.trend}</span></div>{latest.slice(0,4).map((r:any,i:number)=><Card key={r.id} r={r} l={l} src={i===0?hurl:FALLBACK_IMAGES[(i+1)%FALLBACK_IMAGES.length]}/>)}</aside></section>
  <section className="icon-grid">{[[t.jobs,"💼","blue"],[t.education,"🎓","blue"],[t.exams,"▣","orange"],[t.results,"♢","green"],[t.government,"♜","pink"],[t.weather,"☀","blue"],[t.sports,"⚽","red"],[t.business,"♣","purple"],[t.technology,"◉","blue"],[t.ent,"♥","pink"]].map(([x,ic,c])=><Link className="icon-tile" href={pre+"/news"} key={x as string}><b className={c as string}>{ic}</b><span>{x}</span><small>{x===t.jobs?t.jobs:x===t.education?t.education:t.update}</small></Link>)}</section>
  <section className="mobile-latest"><div className="mobile-section-head"><div><span>আজকের আপডেট</span><h2>{t.recent}</h2></div><Link href={pre+"/news"}>{t.all}</Link></div><div className="mobile-story-list">{latest.slice(0,4).map((r:any,i:number)=><Link className="mobile-story" key={r.id} href={r?.slug?"/article?slug="+encodeURIComponent(r.slug)+"&locale="+l:pre+"/news"}><Img src={i===0?hurl:FALLBACK_IMAGES[(i+1)%FALLBACK_IMAGES.length]} alt={titleOf(r,l)}/><div><small>{catOf(r,l,"News")}</small><b>{titleOf(r,l)}</b><span>◷ {i+2} ঘণ্টা আগে　•　◉ {(12-i*2)+"K"} views</span></div></Link>)}</div></section>\n  <section className="three-cols"><InfoBox title={t.jobs} rows={J.slice(0,4)} l={l} type="job"/><InfoBox title={t.education} rows={latest.slice(0,4)} l={l}/><InfoBox title={t.resultsTitle} rows={latest.slice(0,4)} l={l}/></section>
  <section className="lower-grid"><div><div className="sec-title"><h2>{t.jobs}</h2><Link href={pre+"/jobs"}>{t.more}</Link></div><div className="job-table">{J.slice(0,3).map((j:any)=><Link href={pre+"/jobs"} key={j.id}><b>{titleOf(j,l)}</b><span>{j.location||"West Bengal"}　•　{t.lastDate}</span><em>{t.view}</em></Link>)}</div></div>
  <div><div className="sec-title"><h2>{t.ai}</h2></div><div className="tools-box">{[t.toolsPdf,t.toolsImage,t.toolsText,t.toolsLanguage,t.toolsCareer,t.toolsStudent,t.toolsFinance,t.toolsDeveloper].map(x=><Link href={pre+"/ai-tools"} key={x}><b>▣</b><span>{x}</span><small>{t.easyTool}</small></Link>)}</div></div></section>  <section className="footer-banner"><h2>{l==="bn"?"কিচলচে — খবর, চাকরি, শিক্ষা ও জরুরি তথ্য এক জায়গায়":l==="hi"?"किचोलचे — समाचार, नौकरी, शिक्षा और जरूरी जानकारी एक जगह":"Kicholche — News, Jobs, Education & Important Information in One Place"}</h2><Link href={pre+"/news"}>{t.more}</Link></section>
 </div>
 <footer className="footer-slim"><span>কিচলচে</span><b>{t.news}</b><b>{t.jobs}</b><b>{t.education}</b><b>{t.resultsTitle}</b><b>{t.governmentUpdate}</b><b>{t.importantLinks}</b><strong>kicholche.com</strong><small>{t.copyright}</small></footer>
 <nav className="bottom-nav"><Link className="active" href={pre}>⌂<span>{t.home}</span></Link><Link href={pre+"/jobs"}>💼<span>{t.jobs}</span></Link><Link href={pre+"/news"}>⌕<span>{t.latest}</span></Link><Link href={pre+"/ai-tools"}>♧<span>{t.tools}</span></Link><Link href={"/account?locale="+l}>♙<span>{t.account}</span></Link></nav>
 </main></>
}
function InfoBox({title,rows,l,type}:{title:string,rows:any[],l:Locale,type?:string}){return <div className="info-box"><div className="sec-title"><h2>{title}</h2><Link href={"/"+l+(type==="job"?"/jobs":"/news")}>{l==="bn"?"সব দেখুন →":l==="hi"?"सभी देखें →":"View all →"}</Link></div>{rows.map((r:any,i:number)=><Link className="mini-row" href={type==="job"?"/"+l+"/jobs":"/article?slug="+encodeURIComponent(r.slug)+"&locale="+l} key={r.id}><Img kind={type==="job"?"job":"news"}/><div><b>{titleOf(r,l)}</b><small>{type==="job"?(r.job_type||"Government Job"):((l==="bn"?"মাধ্যমিক শিক্ষা পর্ষদ":l==="hi"?"माध्यमिक शिक्षा बोर्ड":"Education Board")+"　•　"+(i+2)+(l==="bn"?" ঘণ্টা আগে":l==="hi"?" घंटे पहले":" hours ago"))}</small></div></Link>)}</div>}
