revoke execute on function public.handle_new_user() from anon, authenticated;
revoke execute on function public.is_admin() from anon, authenticated;
revoke execute on function public.is_manager() from anon, authenticated;
drop policy if exists "users own saved articles" on public.saved_articles; create policy "users own saved articles" on public.saved_articles for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists "users own saved jobs" on public.saved_jobs; create policy "users own saved jobs" on public.saved_jobs for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists "users own preferences" on public.user_preferences; create policy "users own preferences" on public.user_preferences for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists "users own tool usage" on public.tool_usage; create policy "users own tool usage" on public.tool_usage for select to authenticated using((select auth.uid())=user_id);
alter table public.tool_usage drop constraint if exists tool_usage_pkey; alter table public.tool_usage add primary key (tool_id,used_at,user_id);
create index if not exists idx_analytics_user_id on public.analytics_events(user_id); create index if not exists idx_articles_author_id on public.articles(author_id); create index if not exists idx_articles_featured_media_id on public.articles(featured_media_id); create index if not exists idx_audit_logs_actor_id on public.audit_logs(actor_id); create index if not exists idx_media_created_by on public.media(created_by); create index if not exists idx_role_permissions_permission_id on public.role_permissions(permission_id); create index if not exists idx_saved_articles_article_id on public.saved_articles(article_id); create index if not exists idx_saved_jobs_job_id on public.saved_jobs(job_id); create index if not exists idx_tool_usage_tool_id on public.tool_usage(tool_id); create index if not exists idx_tool_usage_user_id on public.tool_usage(user_id);
